boosthist:
  - ./data/merged-histogram-cairo-2018.pkl.gz

xsections:
  !include ./config/xsections_2018.yaml

luminosity: 
  value: 60.0
  uncer: 1.025

groups:
  WW:
    processes:
      - WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8
      - GluGluToWWToENEN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToENMN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToENTN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToMNMN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToMNEN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToMNTN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToTNMN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToTNTN_TuneCP5_13TeV_MCFM701_pythia8
      - VBS_OSWW_LL_TuneCP5_13TeV-madgraph-pythia8
      - VBS_OSWW_TT_TuneCP5_13TeV-madgraph-pythia8
      - VBS_OSWW_TL_TuneCP5_13TeV-madgraph-pythia8
      - VBS_OSWW_LT_TuneCP5_13TeV-madgraph-pythia8
    type:
      background
  WZ:
    processes:
      - WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8
      - WZJJ_EWK_InclusivePolarization_TuneCP5_13TeV_madgraph-madspin-pythia8
    type:
      background
  DY:
    processes:
      - DYJetsToTauTau_M-50_AtLeastOneEorMuDecay_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos
      - DYJetsToLL_LHEFilterPtZ-0To50_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
      - DYJetsToLL_LHEFilterPtZ-50To100_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
      - DYJetsToLL_LHEFilterPtZ-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
      - DYJetsToLL_LHEFilterPtZ-250To400_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
      - DYJetsToLL_LHEFilterPtZ-400To650_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
      - DYJetsToLL_LHEFilterPtZ-650ToInf_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8
      - EWKZ2Jets_ZToLL_M-50_TuneCP5_withDipoleRecoil_13TeV-madgraph-pythia8
    type:
      background
  TOP:
    processes:
      - ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8
      - ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8
      - ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/.root
      - ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8
      - ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8
      - tZq_ll_4f_ckm_NLO_TuneCP5_13TeV-amcatnlo-pythia8
      - TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8
      - TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8
      - TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8
      - TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8
      - TTZToQQ_TuneCP5_13TeV-amcatnlo-pythia8
    type:
      background
  VVV:
    processes:
      - WWZ_4F_TuneCP5_13TeV-amcatnlo-pythia8
      - WZZ_TuneCP5_13TeV-amcatnlo-pythia8
      - ZZZ_TuneCP5_13TeV-amcatnlo-pythia8
      - GluGluToContinToZZTo2e2mu_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo2e2tau_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo2mu2tau_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo4e_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo4mu_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo4tau_TuneCP5_13TeV-mcfm701-pythia8
    type:
      background
  VBSZZ2l2nu:
    processes:
      - ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8
      - GluGluToContinToZZTo2e2nu_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo2mu2nu_TuneCP5_13TeV-mcfm701-pythia8
    type:
      signal
  ZZ2l2nu:
    processes:
      - ZZJJ_ZZTo2L2Nu_EWK_dipoleRecoil_TuneCP5_13TeV-madgraph-pythia8
    type:
      signal
  data:
    processes:
      - MuonEG
      - DoubleMuon
      - SingleMuon
      - EGamma
    type:
      data
