VVV:
  files:
    - ./eos/WWZ_4F_TuneCP5_13TeV-amcatnlo-pythia8/merge.root
    - ./eos/WZZ_TuneCP5_13TeV-amcatnlo-pythia8/merge.root
    - ./eos/ZZZ_TuneCP5_13TeV-amcatnlo-pythia8/merge.root
  type:
    background
  color: 38
ZZ:
  files:
    - ./eos/ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/merge.root
    - ./eos/GluGluToContinToZZTo2e2mu_TuneCP5_13TeV-mcfm701-pythia8/merge.root
    - ./eos/GluGluToContinToZZTo2e2tau_TuneCP5_13TeV-mcfm701-pythia8/merge.root
    - ./eos/GluGluToContinToZZTo2e2nu_TuneCP5_13TeV-mcfm701-pythia8/merge.root
    - ./eos/GluGluToContinToZZTo2mu2tau_TuneCP5_13TeV-mcfm701-pythia8/merge.root
    - ./eos/GluGluToContinToZZTo2mu2nu_TuneCP5_13TeV-mcfm701-pythia8/merge.root
    - ./eos/GluGluToContinToZZTo4e_TuneCP5_13TeV-mcfm701-pythia8/merge.root
    - ./eos/GluGluToContinToZZTo4mu_TuneCP5_13TeV-mcfm701-pythia8/merge.root
    - ./eos/GluGluToContinToZZTo4tau_TuneCP5_13TeV-mcfm701-pythia8/merge.root
  type:
    background
  color: 798
WW:
  files:
    - ./eos/WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/merge.root
    - ./eos/GluGluToWWToENEN_TuneCP5_13TeV_MCFM701_pythia8/merge.root
    - ./eos/GluGluToWWToENMN_TuneCP5_13TeV_MCFM701_pythia8/merge.root
    - ./eos/GluGluToWWToENTN_TuneCP5_13TeV_MCFM701_pythia8/merge.root
    - ./eos/GluGluToWWToMNMN_TuneCP5_13TeV_MCFM701_pythia8/merge.root
    - ./eos/GluGluToWWToMNEN_TuneCP5_13TeV_MCFM701_pythia8/merge.root
    - ./eos/GluGluToWWToMNTN_TuneCP5_13TeV_MCFM701_pythia8/merge.root
    - ./eos/GluGluToWWToTNMN_TuneCP5_13TeV_MCFM701_pythia8/merge.root
    - ./eos/GluGluToWWToTNTN_TuneCP5_13TeV_MCFM701_pythia8/merge.root
    - ./eos/VBS_OSWW_LL_TuneCP5_13TeV-madgraph-pythia8/merge.root
    - ./eos/VBS_OSWW_TT_TuneCP5_13TeV-madgraph-pythia8/merge.root
    - ./eos/VBS_OSWW_TL_TuneCP5_13TeV-madgraph-pythia8/merge.root
    - ./eos/VBS_OSWW_LT_TuneCP5_13TeV-madgraph-pythia8/merge.root
  type:
    background
  color: 842
VBS:
  files:
    - ./eos/ZZJJ_ZZTo2L2Nu_EWK_dipoleRecoil_TuneCP5_13TeV-madgraph-pythia8/merge.root
  type:
    background
  color: 895
WZ:
  files:
    - ./eos/WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8/merge.root
    - ./eos/WZJJ_EWK_InclusivePolarization_TuneCP5_13TeV_madgraph-madspin-pythia8/merge.root
  type:
    background
  kfactor: 1.23
  color: 856
DY:
  files:
    - ./eos/DYJetsToTauTau_M-50_AtLeastOneEorMuDecay_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/merge.root
    - ./eos/DYJetsToLL_M-50_HT-70to100_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/merge.root
    - ./eos/DYJetsToLL_M-50_HT-100to200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/merge.root
    - ./eos/DYJetsToLL_M-50_HT-200to400_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/merge.root
    - ./eos/DYJetsToLL_M-50_HT-400to600_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/merge.root
    - ./eos/DYJetsToLL_M-50_HT-600to800_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/merge.root
    - ./eos/DYJetsToLL_M-50_HT-800to1200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/merge.root
    - ./eos/DYJetsToLL_M-50_HT-1200to2500_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/merge.root
    - ./eos/DYJetsToLL_M-50_HT-2500toInf_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/merge.root
    - ./eos/EWKZ2Jets_ZToLL_M-50_TuneCP5_withDipoleRecoil_13TeV-madgraph-pythia8/merge.root
  type:
    background
  kfactor: 1.0
  color: 901
TOP:
  files:
    - ./eos/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8/merge.root
    - ./eos/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8/merge.root
    - ./eos/ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/merge.root
    - ./eos/ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/merge.root
    - ./eos/ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8/merge.root
    - ./eos/tZq_ll_4f_ckm_NLO_TuneCP5_13TeV-amcatnlo-pythia8/merge.root
    - ./eos/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/merge.root
    - ./eos/TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8/merge.root
    - ./eos/TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8/merge.root
    - ./eos/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/merge.root
    - ./eos/TTZToQQ_TuneCP5_13TeV-amcatnlo-pythia8/merge.root
  type:
    background
  color: 124
  kfactor: 1.0
data:
  files:
    - ./eos/DoubleMuon_Run2018A-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
    - ./eos/DoubleMuon_Run2018B-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
    - ./eos/DoubleMuon_Run2018C-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
    - ./eos/DoubleMuon_Run2018D-UL2018_MiniAODv2_NanoAODv9-v2/merge.root
    - ./eos/EGamma_Run2018A-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
    - ./eos/EGamma_Run2018B-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
    - ./eos/EGamma_Run2018C-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
    - ./eos/EGamma_Run2018D-UL2018_MiniAODv2_NanoAODv9-v3/merge.root
    - ./eos/MuonEG_Run2018A-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
    - ./eos/MuonEG_Run2018B-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
    - ./eos/MuonEG_Run2018C-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
    - ./eos/MuonEG_Run2018D-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
    - ./eos/SingleMuon_Run2018A-UL2018_MiniAODv2_NanoAODv9-v2/merge.root
    - ./eos/SingleMuon_Run2018B-UL2018_MiniAODv2_NanoAODv9-v2/merge.root
    - ./eos/SingleMuon_Run2018C-UL2018_MiniAODv2_NanoAODv9-v2/merge.root
    - ./eos/SingleMuon_Run2018D-UL2018_MiniAODv2_NanoAODv9-v1/merge.root
  type:
    data
  color: 1
