boosthist:
  - ./data/histogram-vbs-zz-2018.pkl.gz

xsections:
  !include ./config/xsections_2018.yaml

luminosity: 
  value: 60.0
  uncer: 1.025

groups:
  WW:
    processes:
      - WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8
      - GluGluToWWToENEN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToENMN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToENTN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToMNMN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToMNEN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToMNTN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToTNMN_TuneCP5_13TeV_MCFM701_pythia8
      - GluGluToWWToTNTN_TuneCP5_13TeV_MCFM701_pythia8
      - VBS_OSWW_LL_TuneCP5_13TeV-madgraph-pythia8
      - VBS_OSWW_TT_TuneCP5_13TeV-madgraph-pythia8
      - VBS_OSWW_TL_TuneCP5_13TeV-madgraph-pythia8
      - VBS_OSWW_LT_TuneCP5_13TeV-madgraph-pythia8
    type:
      background
  WZ:
    processes:
      - WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8
      - WZJJ_EWK_InclusivePolarization_TuneCP5_13TeV_madgraph-madspin-pythia8
    type:
      background
  DY:
    processes:
      - DYJetsToTauTau_M-50_AtLeastOneEorMuDecay_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos
      - DYJetsToLL_M-50_HT-70to100_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
      - DYJetsToLL_M-50_HT-100to200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
      - DYJetsToLL_M-50_HT-200to400_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
      - DYJetsToLL_M-50_HT-400to600_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
      - DYJetsToLL_M-50_HT-600to800_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
      - DYJetsToLL_M-50_HT-800to1200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
      - DYJetsToLL_M-50_HT-1200to2500_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
      - DYJetsToLL_M-50_HT-2500toInf_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
      - EWKZ2Jets_ZToLL_M-50_TuneCP5_withDipoleRecoil_13TeV-madgraph-pythia8
    type:
      background
  TOP:
    processes:
      - ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8
      - ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8
      - ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/.root
      - ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8
      - ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8
      - tZq_ll_4f_ckm_NLO_TuneCP5_13TeV-amcatnlo-pythia8
      - TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8
      - TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8
      - TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8
      - TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8
      - TTZToQQ_TuneCP5_13TeV-amcatnlo-pythia8
    type:
      background
  VVV:
    processes:
      - WWZ_4F_TuneCP5_13TeV-amcatnlo-pythia8
      - WZZ_TuneCP5_13TeV-amcatnlo-pythia8
      - ZZZ_TuneCP5_13TeV-amcatnlo-pythia8
    type:
      background
  VBS_qcd:
    processes:
      - ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8
      - GluGluToContinToZZTo2e2mu_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo2e2tau_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo2e2nu_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo2mu2tau_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo2mu2nu_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo4e_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo4mu_TuneCP5_13TeV-mcfm701-pythia8
      - GluGluToContinToZZTo4tau_TuneCP5_13TeV-mcfm701-pythia8
    type:
      signal
  VBS_ewk:
    processes:
      - ZZJJ_ZZTo2L2Nu_EWK_dipoleRecoil_TuneCP5_13TeV-madgraph-pythia8
    type:
      signal
  data:
    processes:
      - SingleMuon_Run2018D-UL2018_MiniAODv2_NanoAODv9-v1
      - SingleMuon_Run2018A-UL2018_MiniAODv2_NanoAODv9-v2
      - SingleMuon_Run2018B-UL2018_MiniAODv2_NanoAODv9-v2
      - SingleMuon_Run2018C-UL2018_MiniAODv2_NanoAODv9-v2
      - MuonEG_Run2018A-UL2018_MiniAODv2_NanoAODv9-v1
      - MuonEG_Run2018C-UL2018_MiniAODv2_NanoAODv9-v1
      - MuonEG_Run2018B-UL2018_MiniAODv2_NanoAODv9-v1
      - MuonEG_Run2018D-UL2018_MiniAODv2_NanoAODv9-v1
      - EGamma_Run2018D-UL2018_MiniAODv2_NanoAODv9-v3
      - EGamma_Run2018B-UL2018_MiniAODv2_NanoAODv9-v1
      - EGamma_Run2018A-UL2018_MiniAODv2_NanoAODv9-v1
      - EGamma_Run2018C-UL2018_MiniAODv2_NanoAODv9-v1
      - DoubleMuon_Run2018C-UL2018_MiniAODv2_NanoAODv9-v1
      - DoubleMuon_Run2018A-UL2018_MiniAODv2_NanoAODv9-v1
      - DoubleMuon_Run2018D-UL2018_MiniAODv2_NanoAODv9-v2
      - DoubleMuon_Run2018B-UL2018_MiniAODv2_NanoAODv9-v1
    type:
      data
